server:
  port: 8761
spring:
  application:
    name: eureka-server
    title: ${application.title}
    version: ${application.version}
  zipkin:
    base-url: http://zipkin:9411
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false